### ISSUE TITLE
Internal server error edge case

### ISSUE THREAD

**Issue by ArkadiuszMichalRys** [sixoverground/icotar#1]
killer12345 will cause an internal server error on https://icotar.com.

https://icotar.com/avatar/killer12345

**Comment by craigphares** [comment]
Verified! Looks like one of the icons is 48px, not 24px. Good catch.

**Comment by p0n1** [comment]
BTW https://icotar.com/avatar/catt caused error too.

**Comment by craigphares** [comment]
All good now. Both couches 🛋
